const fs = require('fs')
const path = require('path')

module.exports = {
    name: 'html',
    alias: ['tohtml', 'text2html', 'webpage'],
    category: 'Documents',
    desc: 'Convert text to simple .html document',

    execute: async (sock, m, { args, reply, prefix }) => {
        try {
            let text = ''

            // Get text from args
            if (args.length > 0) {
                text = args.join(' ')
            }

            // Fallback to quoted message text
            if (!text && m.quoted) {
                text = (m.quoted.text || m.quoted.caption || '').trim()
            }

            if (!text) {
                return reply(
                    `⚉ Provide text or reply to a message!\n` +
                    `Example: ${prefix}html Hello this is my webpage\n` +
                    `Or reply to text → ${prefix}html`
                )
            }

            // Limit length (HTML can handle a lot, but safety)
            if (text.length > 15000) {
                text = text.substring(0, 14997) + '...'
            }

            await reply('_✦ Creating simple .html document..._')

            // Basic HTML template with styling
            const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRYSNOVA Text Document</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
            text-align: center;
        }
        pre, code {
            background: #f1f1f1;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 0.9em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>CRYSNOVA AI Text Document</h1>
        <pre>${text.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br>')}</pre>
        <div class="footer">
            Generated by CRYSNOVA AI • ${new Date().toLocaleString('en-NG')}
        </div>
    </div>
</body>
</html>
            `

            const tempDir = path.join(__dirname, '../../temp')
            if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true })

            const fileName = `document_${Date.now()}.html`
            const filePath = path.join(tempDir, fileName)

            fs.writeFileSync(filePath, htmlContent)

            const buffer = fs.readFileSync(filePath)

            await sock.sendMessage(m.chat, {
                document: buffer,
                mimetype: 'text/html',
                fileName: fileName,
                caption: `_*𓉤 .html document created*_\n_*Text length:*_ ${text.length} chars`
            }, { quoted: m })

            reply('_*✦ Sent as .html webpage! Tap to open in browser.*_')

            // Cleanup
            fs.unlinkSync(filePath)

        } catch (e) {
            console.log('[HTML ERROR]', e.message)
            reply('✘ Failed to create .html document')
        }
    }
}